// AUTO-GENERATED by scripts/generate-coding-index.mjs - do not edit by hand.
import type { CodingTrackKey } from "./codingTracks";

export type CodingLessonMeta = {
  track: CodingTrackKey;
  slug: string;
  dayLabel: string;
  title: string;
  order: number;
  fileName: string;
  contentPath: string;
  hasSolution: boolean;
  solutionPath: string | null;
};

export const codingLessons: CodingLessonMeta[] = [
  {
    "track": "javascript",
    "slug": "day-001-variables-and-output",
    "dayLabel": "Day 1",
    "title": "Variables & Output",
    "order": 1,
    "fileName": "day-001-variables-and-output.md",
    "contentPath": "coding/JavaScript/day-001-variables-and-output.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-001-variables-and-output.md"
  },
  {
    "track": "javascript",
    "slug": "day-002-data-types",
    "dayLabel": "Day 2",
    "title": "Data Types",
    "order": 2,
    "fileName": "day-002-data-types.md",
    "contentPath": "coding/JavaScript/day-002-data-types.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-002-data-types.md"
  },
  {
    "track": "javascript",
    "slug": "day-003-type-conversion",
    "dayLabel": "Day 3",
    "title": "Type Conversion",
    "order": 3,
    "fileName": "day-003-type-conversion.md",
    "contentPath": "coding/JavaScript/day-003-type-conversion.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-003-type-conversion.md"
  },
  {
    "track": "javascript",
    "slug": "day-004-arithmetic-operators",
    "dayLabel": "Day 4",
    "title": "Arithmetic Operators",
    "order": 4,
    "fileName": "day-004-arithmetic-operators.md",
    "contentPath": "coding/JavaScript/day-004-arithmetic-operators.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-004-arithmetic-operators.md"
  },
  {
    "track": "javascript",
    "slug": "day-005-comparison-operators",
    "dayLabel": "Day 5",
    "title": "Comparison Operators",
    "order": 5,
    "fileName": "day-005-comparison-operators.md",
    "contentPath": "coding/JavaScript/day-005-comparison-operators.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-005-comparison-operators.md"
  },
  {
    "track": "javascript",
    "slug": "day-006-logical-operators",
    "dayLabel": "Day 6",
    "title": "Logical Operators",
    "order": 6,
    "fileName": "day-006-logical-operators.md",
    "contentPath": "coding/JavaScript/day-006-logical-operators.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-006-logical-operators.md"
  },
  {
    "track": "javascript",
    "slug": "day-007-conditional-practice",
    "dayLabel": "Day 7",
    "title": "Conditional Practice",
    "order": 7,
    "fileName": "day-007-conditional-practice.md",
    "contentPath": "coding/JavaScript/day-007-conditional-practice.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-007-conditional-practice.md"
  },
  {
    "track": "javascript",
    "slug": "day-008-ternary-and-switch",
    "dayLabel": "Day 8",
    "title": "Ternary & Switch",
    "order": 8,
    "fileName": "day-008-ternary-and-switch.md",
    "contentPath": "coding/JavaScript/day-008-ternary-and-switch.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-008-ternary-and-switch.md"
  },
  {
    "track": "javascript",
    "slug": "day-009-functions",
    "dayLabel": "Day 9",
    "title": "Functions",
    "order": 9,
    "fileName": "day-009-functions.md",
    "contentPath": "coding/JavaScript/day-009-functions.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-009-functions.md"
  },
  {
    "track": "javascript",
    "slug": "day-010-function-parameters",
    "dayLabel": "Day 10",
    "title": "Function Parameters",
    "order": 10,
    "fileName": "day-010-function-parameters.md",
    "contentPath": "coding/JavaScript/day-010-function-parameters.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-010-function-parameters.md"
  },
  {
    "track": "javascript",
    "slug": "day-011-arrow-functions",
    "dayLabel": "Day 11",
    "title": "Arrow Functions",
    "order": 11,
    "fileName": "day-011-arrow-functions.md",
    "contentPath": "coding/JavaScript/day-011-arrow-functions.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-011-arrow-functions.md"
  },
  {
    "track": "javascript",
    "slug": "day-012-truthy-falsy",
    "dayLabel": "Day 12",
    "title": "Truthy/Falsy",
    "order": 12,
    "fileName": "day-012-truthy-falsy.md",
    "contentPath": "coding/JavaScript/day-012-truthy-falsy.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-012-truthy-falsy.md"
  },
  {
    "track": "javascript",
    "slug": "day-013-events",
    "dayLabel": "Day 13",
    "title": "Events (Browser)",
    "order": 13,
    "fileName": "day-013-events.md",
    "contentPath": "coding/JavaScript/day-013-events.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-013-events.md"
  },
  {
    "track": "javascript",
    "slug": "day-014-local-storage",
    "dayLabel": "Day 14",
    "title": "Local Storage",
    "order": 14,
    "fileName": "day-014-local-storage.md",
    "contentPath": "coding/JavaScript/day-014-local-storage.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-014-local-storage.md"
  },
  {
    "track": "javascript",
    "slug": "day-015-module-1-project",
    "dayLabel": "Day 15",
    "title": "Module 1 Project: Expense Tracker",
    "order": 15,
    "fileName": "day-015-module-1-project.md",
    "contentPath": "coding/JavaScript/day-015-module-1-project.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-015-module-1-project.md"
  },
  {
    "track": "javascript",
    "slug": "day-016-loop-basics",
    "dayLabel": "Day 16",
    "title": "Loop Basics",
    "order": 16,
    "fileName": "day-016-loop-basics.md",
    "contentPath": "coding/JavaScript/day-016-loop-basics.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-016-loop-basics.md"
  },
  {
    "track": "javascript",
    "slug": "day-017-while-and-do-while",
    "dayLabel": "Day 17",
    "title": "while & do...while",
    "order": 17,
    "fileName": "day-017-while-and-do-while.md",
    "contentPath": "coding/JavaScript/day-017-while-and-do-while.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-017-while-and-do-while.md"
  },
  {
    "track": "javascript",
    "slug": "day-018-break-and-continue",
    "dayLabel": "Day 18",
    "title": "break & continue",
    "order": 18,
    "fileName": "day-018-break-and-continue.md",
    "contentPath": "coding/JavaScript/day-018-break-and-continue.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-018-break-and-continue.md"
  },
  {
    "track": "javascript",
    "slug": "day-019-nested-loops",
    "dayLabel": "Day 19",
    "title": "Nested Loops",
    "order": 19,
    "fileName": "day-019-nested-loops.md",
    "contentPath": "coding/JavaScript/day-019-nested-loops.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-019-nested-loops.md"
  },
  {
    "track": "javascript",
    "slug": "day-020-number-problems",
    "dayLabel": "Day 20",
    "title": "Number Problems",
    "order": 20,
    "fileName": "day-020-number-problems.md",
    "contentPath": "coding/JavaScript/day-020-number-problems.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-020-number-problems.md"
  },
  {
    "track": "javascript",
    "slug": "day-021-more-number-problems",
    "dayLabel": "Day 21",
    "title": "More Number Problems",
    "order": 21,
    "fileName": "day-021-more-number-problems.md",
    "contentPath": "coding/JavaScript/day-021-more-number-problems.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-021-more-number-problems.md"
  },
  {
    "track": "javascript",
    "slug": "day-022-for-of-practice",
    "dayLabel": "Day 22",
    "title": "for...of Practice",
    "order": 22,
    "fileName": "day-022-for-of-practice.md",
    "contentPath": "coding/JavaScript/day-022-for-of-practice.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-022-for-of-practice.md"
  },
  {
    "track": "javascript",
    "slug": "day-023-for-in-practice",
    "dayLabel": "Day 23",
    "title": "for...in Practice",
    "order": 23,
    "fileName": "day-023-for-in-practice.md",
    "contentPath": "coding/JavaScript/day-023-for-in-practice.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-023-for-in-practice.md"
  },
  {
    "track": "javascript",
    "slug": "day-024-string-problems",
    "dayLabel": "Day 24",
    "title": "String Problems",
    "order": 24,
    "fileName": "day-024-string-problems.md",
    "contentPath": "coding/JavaScript/day-024-string-problems.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-024-string-problems.md"
  },
  {
    "track": "javascript",
    "slug": "day-025-pattern-problems",
    "dayLabel": "Day 25",
    "title": "Pattern Problems",
    "order": 25,
    "fileName": "day-025-pattern-problems.md",
    "contentPath": "coding/JavaScript/day-025-pattern-problems.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-025-pattern-problems.md"
  },
  {
    "track": "javascript",
    "slug": "day-026-problem-solving-challenge",
    "dayLabel": "Day 26",
    "title": "Problem-Solving Challenge (Mixed, No Hints)",
    "order": 26,
    "fileName": "day-026-problem-solving-challenge.md",
    "contentPath": "coding/JavaScript/day-026-problem-solving-challenge.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-026-problem-solving-challenge.md"
  },
  {
    "track": "javascript",
    "slug": "day-027-module-2-assessment",
    "dayLabel": "Day 27",
    "title": "Module 2 Assessment (30 Problems)",
    "order": 27,
    "fileName": "day-027-module-2-assessment.md",
    "contentPath": "coding/JavaScript/day-027-module-2-assessment.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-027-module-2-assessment.md"
  },
  {
    "track": "javascript",
    "slug": "day-028-string-methods",
    "dayLabel": "Day 28",
    "title": "String Methods (slice, substring, includes, startsWith, endsWith, trim)",
    "order": 28,
    "fileName": "day-028-string-methods.md",
    "contentPath": "coding/JavaScript/day-028-string-methods.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-028-string-methods.md"
  },
  {
    "track": "javascript",
    "slug": "day-029-string-transformation",
    "dayLabel": "Day 29",
    "title": "String Transformation (replace, replaceAll, split, join, concat)",
    "order": 29,
    "fileName": "day-029-string-transformation.md",
    "contentPath": "coding/JavaScript/day-029-string-transformation.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-029-string-transformation.md"
  },
  {
    "track": "javascript",
    "slug": "day-030-string-interview-problems",
    "dayLabel": "Day 30",
    "title": "String Interview Problems",
    "order": 30,
    "fileName": "day-030-string-interview-problems.md",
    "contentPath": "coding/JavaScript/day-030-string-interview-problems.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-030-string-interview-problems.md"
  },
  {
    "track": "javascript",
    "slug": "day-031-arrays-basics",
    "dayLabel": "Day 31",
    "title": "Arrays Basics",
    "order": 31,
    "fileName": "day-031-arrays-basics.md",
    "contentPath": "coding/JavaScript/day-031-arrays-basics.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-031-arrays-basics.md"
  },
  {
    "track": "javascript",
    "slug": "day-032-array-modification",
    "dayLabel": "Day 32",
    "title": "Array Modification (push, pop, shift, unshift, splice)",
    "order": 32,
    "fileName": "day-032-array-modification.md",
    "contentPath": "coding/JavaScript/day-032-array-modification.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-032-array-modification.md"
  },
  {
    "track": "javascript",
    "slug": "day-033-array-search",
    "dayLabel": "Day 33",
    "title": "Array Search (includes, indexOf, find, findIndex)",
    "order": 33,
    "fileName": "day-033-array-search.md",
    "contentPath": "coding/JavaScript/day-033-array-search.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-033-array-search.md"
  },
  {
    "track": "javascript",
    "slug": "day-034-foreach",
    "dayLabel": "Day 34",
    "title": "forEach()",
    "order": 34,
    "fileName": "day-034-foreach.md",
    "contentPath": "coding/JavaScript/day-034-foreach.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-034-foreach.md"
  },
  {
    "track": "javascript",
    "slug": "day-035-map",
    "dayLabel": "Day 35",
    "title": "map()",
    "order": 35,
    "fileName": "day-035-map.md",
    "contentPath": "coding/JavaScript/day-035-map.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-035-map.md"
  },
  {
    "track": "javascript",
    "slug": "day-036-filter",
    "dayLabel": "Day 36",
    "title": "filter()",
    "order": 36,
    "fileName": "day-036-filter.md",
    "contentPath": "coding/JavaScript/day-036-filter.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-036-filter.md"
  },
  {
    "track": "javascript",
    "slug": "day-037-reduce",
    "dayLabel": "Day 37",
    "title": "reduce()",
    "order": 37,
    "fileName": "day-037-reduce.md",
    "contentPath": "coding/JavaScript/day-037-reduce.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-037-reduce.md"
  },
  {
    "track": "javascript",
    "slug": "day-038-advanced-array-methods",
    "dayLabel": "Day 38",
    "title": "Advanced Array Methods (some, every, sort, reverse, flat, flatMap)",
    "order": 38,
    "fileName": "day-038-advanced-array-methods.md",
    "contentPath": "coding/JavaScript/day-038-advanced-array-methods.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-038-advanced-array-methods.md"
  },
  {
    "track": "javascript",
    "slug": "day-039-array-of-objects",
    "dayLabel": "Day 39",
    "title": "Array of Objects",
    "order": 39,
    "fileName": "day-039-array-of-objects.md",
    "contentPath": "coding/JavaScript/day-039-array-of-objects.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-039-array-of-objects.md"
  },
  {
    "track": "javascript",
    "slug": "day-040-object-basics",
    "dayLabel": "Day 40",
    "title": "Object Basics",
    "order": 40,
    "fileName": "day-040-object-basics.md",
    "contentPath": "coding/JavaScript/day-040-object-basics.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-040-object-basics.md"
  },
  {
    "track": "javascript",
    "slug": "day-041-object-methods",
    "dayLabel": "Day 41",
    "title": "Object Methods (keys, values, entries)",
    "order": 41,
    "fileName": "day-041-object-methods.md",
    "contentPath": "coding/JavaScript/day-041-object-methods.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-041-object-methods.md"
  },
  {
    "track": "javascript",
    "slug": "day-042-destructuring",
    "dayLabel": "Day 42",
    "title": "Destructuring",
    "order": 42,
    "fileName": "day-042-destructuring.md",
    "contentPath": "coding/JavaScript/day-042-destructuring.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-042-destructuring.md"
  },
  {
    "track": "javascript",
    "slug": "day-043-spread-and-rest",
    "dayLabel": "Day 43",
    "title": "Spread & Rest",
    "order": 43,
    "fileName": "day-043-spread-and-rest.md",
    "contentPath": "coding/JavaScript/day-043-spread-and-rest.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-043-spread-and-rest.md"
  },
  {
    "track": "javascript",
    "slug": "day-044-shallow-vs-deep-copy",
    "dayLabel": "Day 44",
    "title": "Shallow vs Deep Copy",
    "order": 44,
    "fileName": "day-044-shallow-vs-deep-copy.md",
    "contentPath": "coding/JavaScript/day-044-shallow-vs-deep-copy.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-044-shallow-vs-deep-copy.md"
  },
  {
    "track": "javascript",
    "slug": "day-045-data-transformation",
    "dayLabel": "Day 45",
    "title": "Data Transformation",
    "order": 45,
    "fileName": "day-045-data-transformation.md",
    "contentPath": "coding/JavaScript/day-045-data-transformation.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-045-data-transformation.md"
  },
  {
    "track": "javascript",
    "slug": "day-046-real-world-data-challenge",
    "dayLabel": "Day 46",
    "title": "Real-World Data Challenge: E-Commerce Product Processor",
    "order": 46,
    "fileName": "day-046-real-world-data-challenge.md",
    "contentPath": "coding/JavaScript/day-046-real-world-data-challenge.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-046-real-world-data-challenge.md"
  },
  {
    "track": "javascript",
    "slug": "day-047-module-3-assessment",
    "dayLabel": "Day 47",
    "title": "Module 3 Assessment (40 Problems)",
    "order": 47,
    "fileName": "day-047-module-3-assessment.md",
    "contentPath": "coding/JavaScript/day-047-module-3-assessment.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-047-module-3-assessment.md"
  },
  {
    "track": "javascript",
    "slug": "day-048-scope-practice",
    "dayLabel": "Day 48",
    "title": "Scope Practice",
    "order": 48,
    "fileName": "day-048-scope-practice.md",
    "contentPath": "coding/JavaScript/day-048-scope-practice.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-048-scope-practice.md"
  },
  {
    "track": "javascript",
    "slug": "day-049-hoisting-challenges",
    "dayLabel": "Day 49",
    "title": "Hoisting Challenges (Predict the Output)",
    "order": 49,
    "fileName": "day-049-hoisting-challenges.md",
    "contentPath": "coding/JavaScript/day-049-hoisting-challenges.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-049-hoisting-challenges.md"
  },
  {
    "track": "javascript",
    "slug": "day-050-reference-vs-value",
    "dayLabel": "Day 50",
    "title": "Reference vs Value",
    "order": 50,
    "fileName": "day-050-reference-vs-value.md",
    "contentPath": "coding/JavaScript/day-050-reference-vs-value.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-050-reference-vs-value.md"
  },
  {
    "track": "javascript",
    "slug": "day-051-higher-order-functions",
    "dayLabel": "Day 51",
    "title": "Higher-Order Functions (customMap, customFilter, customForEach, customReduce)",
    "order": 51,
    "fileName": "day-051-higher-order-functions.md",
    "contentPath": "coding/JavaScript/day-051-higher-order-functions.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-051-higher-order-functions.md"
  },
  {
    "track": "javascript",
    "slug": "day-052-callback-functions",
    "dayLabel": "Day 52",
    "title": "Callback Functions (processUser, processOrder, calculate, validate)",
    "order": 52,
    "fileName": "day-052-callback-functions.md",
    "contentPath": "coding/JavaScript/day-052-callback-functions.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-052-callback-functions.md"
  },
  {
    "track": "javascript",
    "slug": "day-053-closures",
    "dayLabel": "Day 53",
    "title": "Closures (Counter, Private Variable, Login Tracker, Bank Account, once)",
    "order": 53,
    "fileName": "day-053-closures.md",
    "contentPath": "coding/JavaScript/day-053-closures.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-053-closures.md"
  },
  {
    "track": "javascript",
    "slug": "day-054-advanced-closure-problems",
    "dayLabel": "Day 54",
    "title": "Advanced Closure Problems (once, memoize, createCounter, createLogger, createIdGenerator)",
    "order": 54,
    "fileName": "day-054-advanced-closure-problems.md",
    "contentPath": "coding/JavaScript/day-054-advanced-closure-problems.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-054-advanced-closure-problems.md"
  },
  {
    "track": "javascript",
    "slug": "day-055-this-keyword",
    "dayLabel": "Day 55",
    "title": "this (Predict the Output, 20 Examples)",
    "order": 55,
    "fileName": "day-055-this-keyword.md",
    "contentPath": "coding/JavaScript/day-055-this-keyword.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-055-this-keyword.md"
  },
  {
    "track": "javascript",
    "slug": "day-056-call-apply-bind",
    "dayLabel": "Day 56",
    "title": "call/apply/bind (borrowFunction, bindFunction)",
    "order": 56,
    "fileName": "day-056-call-apply-bind.md",
    "contentPath": "coding/JavaScript/day-056-call-apply-bind.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-056-call-apply-bind.md"
  },
  {
    "track": "javascript",
    "slug": "day-057-constructor-functions",
    "dayLabel": "Day 57",
    "title": "Constructor Functions (User, Product, Employee, BankAccount)",
    "order": 57,
    "fileName": "day-057-constructor-functions.md",
    "contentPath": "coding/JavaScript/day-057-constructor-functions.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-057-constructor-functions.md"
  },
  {
    "track": "javascript",
    "slug": "day-058-prototype",
    "dayLabel": "Day 58",
    "title": "Prototype (Properties, Methods, Chain, Object.create)",
    "order": 58,
    "fileName": "day-058-prototype.md",
    "contentPath": "coding/JavaScript/day-058-prototype.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-058-prototype.md"
  },
  {
    "track": "javascript",
    "slug": "day-059-prototype-inheritance",
    "dayLabel": "Day 59",
    "title": "Prototype Inheritance (Animal->Dog/Cat, Vehicle->Car/Bike)",
    "order": 59,
    "fileName": "day-059-prototype-inheritance.md",
    "contentPath": "coding/JavaScript/day-059-prototype-inheritance.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-059-prototype-inheritance.md"
  },
  {
    "track": "javascript",
    "slug": "day-060-getters-and-setters",
    "dayLabel": "Day 60",
    "title": "Getters & Setters (BankAccount, User, Employee, Product)",
    "order": 60,
    "fileName": "day-060-getters-and-setters.md",
    "contentPath": "coding/JavaScript/day-060-getters-and-setters.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-060-getters-and-setters.md"
  },
  {
    "track": "javascript",
    "slug": "day-061-advanced-object-challenge",
    "dayLabel": "Day 61",
    "title": "Advanced Object Challenge (deepClone, deepFreeze, isEqual, flattenObject)",
    "order": 61,
    "fileName": "day-061-advanced-object-challenge.md",
    "contentPath": "coding/JavaScript/day-061-advanced-object-challenge.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-061-advanced-object-challenge.md"
  },
  {
    "track": "javascript",
    "slug": "day-062-functional-programming-practice",
    "dayLabel": "Day 62",
    "title": "Functional Programming Practice",
    "order": 62,
    "fileName": "day-062-functional-programming-practice.md",
    "contentPath": "coding/JavaScript/day-062-functional-programming-practice.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-062-functional-programming-practice.md"
  },
  {
    "track": "javascript",
    "slug": "day-063-module-4-interview-challenge",
    "dayLabel": "Day 63",
    "title": "Module 4 Interview Challenge (25 Advanced Questions)",
    "order": 63,
    "fileName": "day-063-module-4-interview-challenge.md",
    "contentPath": "coding/JavaScript/day-063-module-4-interview-challenge.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-063-module-4-interview-challenge.md"
  },
  {
    "track": "javascript",
    "slug": "day-064-classes",
    "dayLabel": "Day 64",
    "title": "Classes (User, Product, Employee, Student)",
    "order": 64,
    "fileName": "day-064-classes.md",
    "contentPath": "coding/JavaScript/day-064-classes.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-064-classes.md"
  },
  {
    "track": "javascript",
    "slug": "day-065-constructors-and-methods",
    "dayLabel": "Day 65",
    "title": "Constructors & Methods: Bank Account System",
    "order": 65,
    "fileName": "day-065-constructors-and-methods.md",
    "contentPath": "coding/JavaScript/day-065-constructors-and-methods.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-065-constructors-and-methods.md"
  },
  {
    "track": "javascript",
    "slug": "day-066-encapsulation",
    "dayLabel": "Day 66",
    "title": "Encapsulation (Private Fields #balance, #password, #salary)",
    "order": 66,
    "fileName": "day-066-encapsulation.md",
    "contentPath": "coding/JavaScript/day-066-encapsulation.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-066-encapsulation.md"
  },
  {
    "track": "javascript",
    "slug": "day-067-getters-and-setters-employee-system",
    "dayLabel": "Day 67",
    "title": "Getters & Setters: Employee Management System",
    "order": 67,
    "fileName": "day-067-getters-and-setters-employee-system.md",
    "contentPath": "coding/JavaScript/day-067-getters-and-setters-employee-system.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-067-getters-and-setters-employee-system.md"
  },
  {
    "track": "javascript",
    "slug": "day-068-inheritance",
    "dayLabel": "Day 68",
    "title": "Inheritance (Person -> Student, Person -> Teacher)",
    "order": 68,
    "fileName": "day-068-inheritance.md",
    "contentPath": "coding/JavaScript/day-068-inheritance.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-068-inheritance.md"
  },
  {
    "track": "javascript",
    "slug": "day-069-polymorphism",
    "dayLabel": "Day 69",
    "title": "Polymorphism (calculateSalary, calculateArea, calculatePayment)",
    "order": 69,
    "fileName": "day-069-polymorphism.md",
    "contentPath": "coding/JavaScript/day-069-polymorphism.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-069-polymorphism.md"
  },
  {
    "track": "javascript",
    "slug": "day-070-composition",
    "dayLabel": "Day 70",
    "title": "Composition (User, Address, Order, Payment, Notification)",
    "order": 70,
    "fileName": "day-070-composition.md",
    "contentPath": "coding/JavaScript/day-070-composition.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-070-composition.md"
  },
  {
    "track": "javascript",
    "slug": "day-071-static-methods",
    "dayLabel": "Day 71",
    "title": "Static Methods (User.validate/create, Product.search/sort)",
    "order": 71,
    "fileName": "day-071-static-methods.md",
    "contentPath": "coding/JavaScript/day-071-static-methods.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-071-static-methods.md"
  },
  {
    "track": "javascript",
    "slug": "day-072-set",
    "dayLabel": "Day 72",
    "title": "Set (union, intersection, difference)",
    "order": 72,
    "fileName": "day-072-set.md",
    "contentPath": "coding/JavaScript/day-072-set.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-072-set.md"
  },
  {
    "track": "javascript",
    "slug": "day-073-map",
    "dayLabel": "Day 73",
    "title": "Map (frequencyCounter, cache, userLookup, productLookup)",
    "order": 73,
    "fileName": "day-073-map.md",
    "contentPath": "coding/JavaScript/day-073-map.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-073-map.md"
  },
  {
    "track": "javascript",
    "slug": "day-074-weakmap-weakset",
    "dayLabel": "Day 74",
    "title": "WeakMap / WeakSet",
    "order": 74,
    "fileName": "day-074-weakmap-weakset.md",
    "contentPath": "coding/JavaScript/day-074-weakmap-weakset.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-074-weakmap-weakset.md"
  },
  {
    "track": "javascript",
    "slug": "day-075-oop-project-shopping-cart",
    "dayLabel": "Day 75",
    "title": "OOP Project: Shopping Cart System",
    "order": 75,
    "fileName": "day-075-oop-project-shopping-cart.md",
    "contentPath": "coding/JavaScript/day-075-oop-project-shopping-cart.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-075-oop-project-shopping-cart.md"
  },
  {
    "track": "javascript",
    "slug": "day-076-module-5-assessment",
    "dayLabel": "Day 76",
    "title": "Module 5 Assessment: Mini Library Management System",
    "order": 76,
    "fileName": "day-076-module-5-assessment.md",
    "contentPath": "coding/JavaScript/day-076-module-5-assessment.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-076-module-5-assessment.md"
  },
  {
    "track": "javascript",
    "slug": "day-077-timers",
    "dayLabel": "Day 77",
    "title": "Timers (setTimeout, setInterval, clearTimeout, clearInterval)",
    "order": 77,
    "fileName": "day-077-timers.md",
    "contentPath": "coding/JavaScript/day-077-timers.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-077-timers.md"
  },
  {
    "track": "javascript",
    "slug": "day-078-callback-async",
    "dayLabel": "Day 78",
    "title": "Callback Async (login, getUser, getOrders, getProducts)",
    "order": 78,
    "fileName": "day-078-callback-async.md",
    "contentPath": "coding/JavaScript/day-078-callback-async.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-078-callback-async.md"
  },
  {
    "track": "javascript",
    "slug": "day-079-callback-hell",
    "dayLabel": "Day 79",
    "title": "Callback Hell",
    "order": 79,
    "fileName": "day-079-callback-hell.md",
    "contentPath": "coding/JavaScript/day-079-callback-hell.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-079-callback-hell.md"
  },
  {
    "track": "javascript",
    "slug": "day-080-promise-basics",
    "dayLabel": "Day 80",
    "title": "Promise Basics",
    "order": 80,
    "fileName": "day-080-promise-basics.md",
    "contentPath": "coding/JavaScript/day-080-promise-basics.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-080-promise-basics.md"
  },
  {
    "track": "javascript",
    "slug": "day-081-promise-chaining",
    "dayLabel": "Day 81",
    "title": "Promise Chaining",
    "order": 81,
    "fileName": "day-081-promise-chaining.md",
    "contentPath": "coding/JavaScript/day-081-promise-chaining.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-081-promise-chaining.md"
  },
  {
    "track": "javascript",
    "slug": "day-082-promise-error-handling",
    "dayLabel": "Day 82",
    "title": "Promise Error Handling",
    "order": 82,
    "fileName": "day-082-promise-error-handling.md",
    "contentPath": "coding/JavaScript/day-082-promise-error-handling.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-082-promise-error-handling.md"
  },
  {
    "track": "javascript",
    "slug": "day-083-promise-all",
    "dayLabel": "Day 83",
    "title": "Promise.all (loadUsers, loadProducts, loadOrders)",
    "order": 83,
    "fileName": "day-083-promise-all.md",
    "contentPath": "coding/JavaScript/day-083-promise-all.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-083-promise-all.md"
  },
  {
    "track": "javascript",
    "slug": "day-084-promise-combinators",
    "dayLabel": "Day 84",
    "title": "Promise Combinators (all, allSettled, race, any)",
    "order": 84,
    "fileName": "day-084-promise-combinators.md",
    "contentPath": "coding/JavaScript/day-084-promise-combinators.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-084-promise-combinators.md"
  },
  {
    "track": "javascript",
    "slug": "day-085-async-await",
    "dayLabel": "Day 85",
    "title": "Async/Await (Convert Promise Solutions)",
    "order": 85,
    "fileName": "day-085-async-await.md",
    "contentPath": "coding/JavaScript/day-085-async-await.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-085-async-await.md"
  },
  {
    "track": "javascript",
    "slug": "day-086-sequential-vs-parallel",
    "dayLabel": "Day 86",
    "title": "Sequential vs Parallel",
    "order": 86,
    "fileName": "day-086-sequential-vs-parallel.md",
    "contentPath": "coding/JavaScript/day-086-sequential-vs-parallel.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-086-sequential-vs-parallel.md"
  },
  {
    "track": "javascript",
    "slug": "day-087-event-loop-challenges",
    "dayLabel": "Day 87",
    "title": "Event Loop Challenges (30 Predict-the-Output Questions)",
    "order": 87,
    "fileName": "day-087-event-loop-challenges.md",
    "contentPath": "coding/JavaScript/day-087-event-loop-challenges.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-087-event-loop-challenges.md"
  },
  {
    "track": "javascript",
    "slug": "day-088-fetch-api",
    "dayLabel": "Day 88",
    "title": "Fetch API (GET, POST, PUT, DELETE)",
    "order": 88,
    "fileName": "day-088-fetch-api.md",
    "contentPath": "coding/JavaScript/day-088-fetch-api.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-088-fetch-api.md"
  },
  {
    "track": "javascript",
    "slug": "day-089-api-data-processing",
    "dayLabel": "Day 89",
    "title": "API Data Processing",
    "order": 89,
    "fileName": "day-089-api-data-processing.md",
    "contentPath": "coding/JavaScript/day-089-api-data-processing.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-089-api-data-processing.md"
  },
  {
    "track": "javascript",
    "slug": "day-090-user-management-dashboard",
    "dayLabel": "Day 90",
    "title": "API Project: User Management Dashboard",
    "order": 90,
    "fileName": "day-090-user-management-dashboard.md",
    "contentPath": "coding/JavaScript/day-090-user-management-dashboard.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-090-user-management-dashboard.md"
  },
  {
    "track": "javascript",
    "slug": "day-091-async-assessment",
    "dayLabel": "Day 91",
    "title": "Async Assessment: Advanced API Challenge",
    "order": 91,
    "fileName": "day-091-async-assessment.md",
    "contentPath": "coding/JavaScript/day-091-async-assessment.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-091-async-assessment.md"
  },
  {
    "track": "javascript",
    "slug": "day-092-dom-selection",
    "dayLabel": "Day 92",
    "title": "DOM Selection: Dynamic User List",
    "order": 92,
    "fileName": "day-092-dom-selection.md",
    "contentPath": "coding/JavaScript/day-092-dom-selection.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-092-dom-selection.md"
  },
  {
    "track": "javascript",
    "slug": "day-093-dom-manipulation",
    "dayLabel": "Day 93",
    "title": "DOM Manipulation (textContent, innerHTML, classList, attributes, styles)",
    "order": 93,
    "fileName": "day-093-dom-manipulation.md",
    "contentPath": "coding/JavaScript/day-093-dom-manipulation.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-093-dom-manipulation.md"
  },
  {
    "track": "javascript",
    "slug": "day-094-create-delete-dom",
    "dayLabel": "Day 94",
    "title": "Create/Delete DOM: Dynamic Todo List",
    "order": 94,
    "fileName": "day-094-create-delete-dom.md",
    "contentPath": "coding/JavaScript/day-094-create-delete-dom.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-094-create-delete-dom.md"
  },
  {
    "track": "javascript",
    "slug": "day-095-dom-events-projects",
    "dayLabel": "Day 95",
    "title": "DOM Events Projects",
    "order": 95,
    "fileName": "day-095-dom-events-projects.md",
    "contentPath": "coding/JavaScript/day-095-dom-events-projects.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-095-dom-events-projects.md"
  },
  {
    "track": "javascript",
    "slug": "day-096-event-bubbling-capturing",
    "dayLabel": "Day 96",
    "title": "Event Bubbling/Capturing Experiment",
    "order": 96,
    "fileName": "day-096-event-bubbling-capturing.md",
    "contentPath": "coding/JavaScript/day-096-event-bubbling-capturing.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-096-event-bubbling-capturing.md"
  },
  {
    "track": "javascript",
    "slug": "day-097-event-delegation",
    "dayLabel": "Day 97",
    "title": "Event Delegation: Dynamic Todo List",
    "order": 97,
    "fileName": "day-097-event-delegation.md",
    "contentPath": "coding/JavaScript/day-097-event-delegation.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-097-event-delegation.md"
  },
  {
    "track": "javascript",
    "slug": "day-098-forms",
    "dayLabel": "Day 98",
    "title": "Forms: Registration Form",
    "order": 98,
    "fileName": "day-098-forms.md",
    "contentPath": "coding/JavaScript/day-098-forms.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-098-forms.md"
  },
  {
    "track": "javascript",
    "slug": "day-099-local-storage-todo-app",
    "dayLabel": "Day 99",
    "title": "Local Storage Project: Todo Application",
    "order": 99,
    "fileName": "day-099-local-storage-todo-app.md",
    "contentPath": "coding/JavaScript/day-099-local-storage-todo-app.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-099-local-storage-todo-app.md"
  },
  {
    "track": "javascript",
    "slug": "day-100-json-data-viewer",
    "dayLabel": "Day 100",
    "title": "JSON Data Viewer",
    "order": 100,
    "fileName": "day-100-json-data-viewer.md",
    "contentPath": "coding/JavaScript/day-100-json-data-viewer.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-100-json-data-viewer.md"
  },
  {
    "track": "javascript",
    "slug": "day-101-es-modules",
    "dayLabel": "Day 101",
    "title": "ES Modules: math.js, user.js, product.js, utils.js, app.js",
    "order": 101,
    "fileName": "day-101-es-modules.md",
    "contentPath": "coding/JavaScript/day-101-es-modules.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-101-es-modules.md"
  },
  {
    "track": "javascript",
    "slug": "day-102-dynamic-import",
    "dayLabel": "Day 102",
    "title": "Dynamic Import: Lazy-Loaded Calculator",
    "order": 102,
    "fileName": "day-102-dynamic-import.md",
    "contentPath": "coding/JavaScript/day-102-dynamic-import.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-102-dynamic-import.md"
  },
  {
    "track": "javascript",
    "slug": "day-103-regex",
    "dayLabel": "Day 103",
    "title": "Regex: Form Validation Engine",
    "order": 103,
    "fileName": "day-103-regex.md",
    "contentPath": "coding/JavaScript/day-103-regex.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-103-regex.md"
  },
  {
    "track": "javascript",
    "slug": "day-104-iterators",
    "dayLabel": "Day 104",
    "title": "Iterators (range, customIterator, paginationIterator)",
    "order": 104,
    "fileName": "day-104-iterators.md",
    "contentPath": "coding/JavaScript/day-104-iterators.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-104-iterators.md"
  },
  {
    "track": "javascript",
    "slug": "day-105-generators",
    "dayLabel": "Day 105",
    "title": "Generators (idGenerator, numberGenerator, passwordGenerator)",
    "order": 105,
    "fileName": "day-105-generators.md",
    "contentPath": "coding/JavaScript/day-105-generators.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-105-generators.md"
  },
  {
    "track": "javascript",
    "slug": "day-106-debounce",
    "dayLabel": "Day 106",
    "title": "Debounce: Search Box",
    "order": 106,
    "fileName": "day-106-debounce.md",
    "contentPath": "coding/JavaScript/day-106-debounce.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-106-debounce.md"
  },
  {
    "track": "javascript",
    "slug": "day-107-throttle",
    "dayLabel": "Day 107",
    "title": "Throttle: Scroll, Resize, Mouse Trackers",
    "order": 107,
    "fileName": "day-107-throttle.md",
    "contentPath": "coding/JavaScript/day-107-throttle.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-107-throttle.md"
  },
  {
    "track": "javascript",
    "slug": "day-108-memory-and-performance",
    "dayLabel": "Day 108",
    "title": "Memory & Performance",
    "order": 108,
    "fileName": "day-108-memory-and-performance.md",
    "contentPath": "coding/JavaScript/day-108-memory-and-performance.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-108-memory-and-performance.md"
  },
  {
    "track": "javascript",
    "slug": "day-109-professional-javascript-challenge",
    "dayLabel": "Day 109",
    "title": "Professional JavaScript Challenge: Personal Utility Library",
    "order": 109,
    "fileName": "day-109-professional-javascript-challenge.md",
    "contentPath": "coding/JavaScript/day-109-professional-javascript-challenge.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-109-professional-javascript-challenge.md"
  },
  {
    "track": "javascript",
    "slug": "day-110-final-coding-challenge",
    "dayLabel": "Day 110",
    "title": "Final Coding Challenge: E-Commerce Management Application",
    "order": 110,
    "fileName": "day-110-final-coding-challenge.md",
    "contentPath": "coding/JavaScript/day-110-final-coding-challenge.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-110-final-coding-challenge.md"
  },
  {
    "track": "javascript",
    "slug": "day-111-sorting-algorithms-1",
    "dayLabel": "Day 111",
    "title": "Sorting Algorithms I (Bubble, Selection, Insertion)",
    "order": 111,
    "fileName": "day-111-sorting-algorithms-1.md",
    "contentPath": "coding/JavaScript/day-111-sorting-algorithms-1.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-111-sorting-algorithms-1.md"
  },
  {
    "track": "javascript",
    "slug": "day-112-sorting-algorithms-2",
    "dayLabel": "Day 112",
    "title": "Sorting Algorithms II (Merge Sort, Quick Sort)",
    "order": 112,
    "fileName": "day-112-sorting-algorithms-2.md",
    "contentPath": "coding/JavaScript/day-112-sorting-algorithms-2.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-112-sorting-algorithms-2.md"
  },
  {
    "track": "javascript",
    "slug": "day-113-searching-algorithms",
    "dayLabel": "Day 113",
    "title": "Searching Algorithms (Linear Search, Binary Search)",
    "order": 113,
    "fileName": "day-113-searching-algorithms.md",
    "contentPath": "coding/JavaScript/day-113-searching-algorithms.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-113-searching-algorithms.md"
  },
  {
    "track": "javascript",
    "slug": "day-114-stack-and-queue",
    "dayLabel": "Day 114",
    "title": "Stack & Queue Implementation",
    "order": 114,
    "fileName": "day-114-stack-and-queue.md",
    "contentPath": "coding/JavaScript/day-114-stack-and-queue.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-114-stack-and-queue.md"
  },
  {
    "track": "javascript",
    "slug": "day-115-linked-list",
    "dayLabel": "Day 115",
    "title": "Linked List Implementation",
    "order": 115,
    "fileName": "day-115-linked-list.md",
    "contentPath": "coding/JavaScript/day-115-linked-list.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-115-linked-list.md"
  },
  {
    "track": "javascript",
    "slug": "day-116-hash-table-and-lru-cache",
    "dayLabel": "Day 116",
    "title": "Hash Table & LRU Cache",
    "order": 116,
    "fileName": "day-116-hash-table-and-lru-cache.md",
    "contentPath": "coding/JavaScript/day-116-hash-table-and-lru-cache.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-116-hash-table-and-lru-cache.md"
  },
  {
    "track": "javascript",
    "slug": "day-117-tree-and-graph-traversal",
    "dayLabel": "Day 117",
    "title": "Tree & Graph Traversal (BFS, DFS)",
    "order": 117,
    "fileName": "day-117-tree-and-graph-traversal.md",
    "contentPath": "coding/JavaScript/day-117-tree-and-graph-traversal.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-117-tree-and-graph-traversal.md"
  },
  {
    "track": "javascript",
    "slug": "day-118-advanced-patterns",
    "dayLabel": "Day 118",
    "title": "Advanced Patterns (Event Emitter, Promise Simulator, Async Retry, Rate Limiter)",
    "order": 118,
    "fileName": "day-118-advanced-patterns.md",
    "contentPath": "coding/JavaScript/day-118-advanced-patterns.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-118-advanced-patterns.md"
  },
  {
    "track": "javascript",
    "slug": "day-119-mini-projects-pack",
    "dayLabel": "Day 119",
    "title": "Mini Projects Pack (DOM + API)",
    "order": 119,
    "fileName": "day-119-mini-projects-pack.md",
    "contentPath": "coding/JavaScript/day-119-mini-projects-pack.md",
    "hasSolution": true,
    "solutionPath": "coding/JavaScript/solutions/day-119-mini-projects-pack.md"
  },
  {
    "track": "javascriptproblemsolving",
    "slug": "day-003-javascript-interview-problem-solving",
    "dayLabel": "Day 3",
    "title": "JavaScript Interview Problem Solving",
    "order": 3,
    "fileName": "day-003-javascript-interview-problem-solving.md",
    "contentPath": "coding/JavaScriptProblemSolving/day-003-javascript-interview-problem-solving.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-001-array-string-problems",
    "dayLabel": "Day 1",
    "title": "Array String Problems",
    "order": 1,
    "fileName": "day-001-array-string-problems.md",
    "contentPath": "coding/JavaScriptRealInterview/day-001-array-string-problems.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-002-output-and-language-questions",
    "dayLabel": "Day 2",
    "title": "Output And Language Questions",
    "order": 2,
    "fileName": "day-002-output-and-language-questions.md",
    "contentPath": "coding/JavaScriptRealInterview/day-002-output-and-language-questions.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-003-polyfills-and-core-apis",
    "dayLabel": "Day 3",
    "title": "Polyfills And Core Apis",
    "order": 3,
    "fileName": "day-003-polyfills-and-core-apis.md",
    "contentPath": "coding/JavaScriptRealInterview/day-003-polyfills-and-core-apis.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-004-practical-dom-async",
    "dayLabel": "Day 4",
    "title": "Practical Dom Async",
    "order": 4,
    "fileName": "day-004-practical-dom-async.md",
    "contentPath": "coding/JavaScriptRealInterview/day-004-practical-dom-async.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-005-company-style-challenges",
    "dayLabel": "Day 5",
    "title": "Company Style Challenges",
    "order": 5,
    "fileName": "day-005-company-style-challenges.md",
    "contentPath": "coding/JavaScriptRealInterview/day-005-company-style-challenges.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-006-100-plus-question-bank",
    "dayLabel": "Day 6",
    "title": "100 Plus Question Bank",
    "order": 6,
    "fileName": "day-006-100-plus-question-bank.md",
    "contentPath": "coding/JavaScriptRealInterview/day-006-100-plus-question-bank.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-007-coding-problem-bank-arrays-and-numbers",
    "dayLabel": "Day 7",
    "title": "JavaScript Interview Coding: Arrays and Numbers",
    "order": 7,
    "fileName": "day-007-coding-problem-bank-arrays-and-numbers.md",
    "contentPath": "coding/JavaScriptRealInterview/day-007-coding-problem-bank-arrays-and-numbers.md",
    "hasSolution": false,
    "solutionPath": null
  },
  {
    "track": "javascriptrealinterview",
    "slug": "day-008-coding-problem-bank-strings-and-objects",
    "dayLabel": "Day 8",
    "title": "JavaScript Interview Coding: Strings and Objects",
    "order": 8,
    "fileName": "day-008-coding-problem-bank-strings-and-objects.md",
    "contentPath": "coding/JavaScriptRealInterview/day-008-coding-problem-bank-strings-and-objects.md",
    "hasSolution": false,
    "solutionPath": null
  }
];

export function getCodingLessonsByTrack(track: CodingTrackKey) {
  return codingLessons
    .filter((lesson) => lesson.track === track)
    .sort((a, b) => a.order - b.order);
}

export function getCodingLessonBySlug(track: CodingTrackKey, slug: string) {
  return codingLessons.find((lesson) => lesson.track === track && lesson.slug === slug);
}

export function getAvailableCodingTracks(): CodingTrackKey[] {
  return Array.from(new Set(codingLessons.map((lesson) => lesson.track)));
}
